- name: Préparation du terrain
  apt:
    name: "python3-docker"
- name: Pull de Miner
  docker_image:
    source: pull
    name: "elestranobaron/muscleupcoin_miner:4197980dfe7ac18bab04160ca3df2a290b860c8e"
#- name: authorize connection X
#  shell: "xhost +"
- name: Create default containers
  vars:
    create_containers: 1
    default_container_name: "{{ dockername }}"
    default_container_image: elestranobaron/muscleupcoin_miner:47772531c9f6a74266bdf888cbffdc1e3693288f
    default_container_command: sleep 1d
    display: :0 #host.docker.internal:0
  docker_container:
    network_mode: host
    name: "{{ default_container_name }}"
    image: "{{ default_container_image }}"
    #etc_hosts: {
    #  host.docker.internal: host-gateway,
    #}
    env: {
           'DISPLAY': "{{ display }}",
    }
    detach: yes
    #command: "{{ default_container_command }}"
    state: started
  with_sequence: count={{ create_containers }}
#- name: Muscleupcoin container
#  docker:
#    name: whateveryouwant
#    state: reloaded
- name: wait for docker service
  service:
    name: docker
    state: started
  register: docker_service
  until: docker_service.status.ActiveState == "active"
  retries: 10
  delay: 20